### ISSUE TITLE
Issue with out-of-date references

### ISSUE THREAD

**Issue by jvdsande** [preactjs/prefresh#404]
Hello!

I'm experiencing an issue with PRefresh, seemingly linked to cyclic dependencies handling.

My setup can be boiled down to the following:

```jsx
// file 1 : components.jsx
import { h, Fragment } from 'preact'
import { Injections } from './injections'

export const Component1 = () => <div>Component 1</div>

export const Component2 = () => (
  <Fragment>
     <Injections.Component1 />
     <div>Component 2</div>
  </Fragment>
)
```

```jsx
// file 2 : injections.jsx
import * as Injections from './components'
```

**(EDIT: for the contrived example to work I actually need a namespace import/reexport otherwise I get a TypeError. Didn't see that because it somehow works if @web/dev-server was already running and we change it to named re-export, maybe a cache issue)**

(Note: this is a simplified reproduction example, the gist of it is I have a dependency injection system that _might_ contain references to components declared in a file, and consumed by another component declared in the same file)

Now while somewhat unorthodox, this setup works correctly in terms of runtime, and I do get the following output:

```html
<div>Component 1</div>
<div>Component 2</div>
```

However, if I edit `Component2`, PRefresh _correctly updates it and rerenders it_, but instantly follows by _reloading the complete page_.

I isolated the reload as coming from those lines in @prefresh/core/index.js:

```js
      // Cleanup when an async component has thrown.
      if (
        (vnode[VNODE_DOM] && !document.contains(vnode[VNODE_DOM])) ||
        (!vnode[VNODE_DOM] && !vnode[VNODE_CHILDREN])
      ) {
        location.reload();  // <-- This is what reloads the page
      }
```

Furthermore I've been able to confirm that the first condition is the one matching (`(vnode[VNODE_DOM] && !document.contains(vnode[VNODE_DOM]))`), and that the culprit VNode is indeed an instance `Component1`.

What I think is happening here, is that when `Component2` triggers the hot-reload, `Component1` gets a de-facto new reference, but `Injections.Component1` at this point still holds the reference to the previous `Component1`.

I'm not sure what this test in @prefresh/core is exactly here for, but I do know that removing it makes everything work correctly again, as far as I can tell. Maybe there is a way to detect this situation and not reload the page?

**Comment by JoviDeCroock** [comment]
This issue is mainly when a `lazy` or `suspenseful` setup happens but throws during the reconciliation it will clear the DOM and won't have an in-memory node-tree. This will improve with Preact v11 but currently I guess we might want to rely on a `setTimeout(() => { /* current condition */ })` if we want to support this use case as then the newly created `Component` has a chance to initialize the DOM.

**Comment by jvdsande** [comment]
Wow, thanks for the quick response!

Ah yes indeed I forgot to mention: this is encountered on `@web/dev-server` using the `@prefresh/web-dev-server` plugin, definitely in a full ESM environment.

**Comment by JoviDeCroock** [comment]
Yes, that has the additional complexity mentioned [here](https://github.com/preactjs/prefresh/pull/236) 😅 we could try the `setTimeout` solution but not entirely sure if it's reliable, I probably won't have time to test it for now

**Comment by jvdsande** [comment]
I tried wrapping the if condition is a `setTimeout` as follows:

```js
      // Cleanup when an async component has thrown.
      setTimeout(()  => {
        if (
          (vnode[VNODE_DOM] && !document.contains(vnode[VNODE_DOM])) ||
          (!vnode[VNODE_DOM] && !vnode[VNODE_CHILDREN])
        ) {
          location.reload();
        }
      }, 1000)
```


But unfortunately my page still reloads, after the second is elapsed

**Comment by JoviDeCroock** [comment]
hmm, that's odd so the circularity probably spawns an abundant amount of VNodes because of the trickling update as we'll be busting both of these. Hmm, I'll need to have a think about this 😅 we could probably enhance this condition or capture it differently but we'd need to research why this circularity is affecting it so much

**Comment by jvdsande** [comment]
Hum... Added a log inside the condition and I confirm it is triggering quite a lot for only one update 😅 

![image](https://user-images.githubusercontent.com/12484011/146210527-9193d22b-b7de-4296-a732-d7fd4c6da4ac.png)

It's not an infinite loop though, at some point it stabilises and the logs stop.

**Comment by JoviDeCroock** [comment]
I wonder if web-dev-server in specific is having issue with how the hmr is triggering updates, it's been a while since I've been involved in their hmr implementation. It probably stops forming an issue when we move `Component1` to its own file? Just wondering here

**Comment by jvdsande** [comment]
Yes, if `Component1` is in its own file, everything works correctly again. Unfortunately this is something I can't control in my real setup

**Comment by twrichards** [comment]
Hi, we (at https://github.com/guardian) observe the same behaviour as @jvdsande describes (i.e. successful HMR, with immediate reload after), but in our case we traced the problem down to our use of shadow DOM, as the the `document.contains` will never find the desired elements. 

I see in https://github.com/preactjs/prefresh/pull/424 (now merged) you've commented out this block, any idea when this will be available in npm? A longer term thought, would be make this reload configurable or perhaps dependant on the value of `hot` property in webpack (for example, not sure if there is equivalent in the other integrations) where `hot: true` will fallback to reload if HMR 'fails', whereas `hot: only` will only attempt HMR and not fallback to reload? @andrew-nowak and/or I are happy to raise a PR if you think this is a good idea.

Thanks

**Comment by JoviDeCroock** [comment]
Hmm we could port it to the v1-migrate-x branch, kinda wanna figure out why this is but probably a similar issue relating to esm-hmr

**Comment by twrichards** [comment]
Yes that would be brilliant, thank you. What are your thoughts on making it configurable?

**Comment by JoviDeCroock** [comment]
Let's not 😅 it's a bit dangerous because of core logic vs integration. We need to find a better way of identifying lazy loaded components that error out

**Comment by twrichards** [comment]
> Let's not 😅 it's a bit dangerous because of core logic vs integration. We need to find a better way of identifying lazy loaded components that error out

Yeah makes total sense. Do we need to raise a PR  to comment out the reload block with base branch `v1-migrate-x` or do you want to cherry-pick that change from main? What's the release process? Ideally we wouldn't want to use a forked version in our application.

**Comment by JoviDeCroock** [comment]
@twrichards this is published

**Comment by twrichards** [comment]
> @twrichards this is published

many thanks @JoviDeCroock
