### ISSUE TITLE
Issue with curried HOC

### ISSUE THREAD

**Issue by jvdsande** [preactjs/prefresh#431]
Hello!

Last December I opened an issue (#404) regarding a problem with HMR when Prefresh encounters out of date references, caused by circular dependencies.

I started reworking my code to stop having to rely on these circular dependencies in the first place, but encountered a second problem in doing so: it seems like Prefresh does not support currying for HOC. 

<details>
  <summary><strong>Reproduction and investigation details</strong></summary>
  <br />
  
  If we take the following code:
  
  ```jsx
  // Dummy curried HOC for reproduction purpose that does nothing interesting...
  const withDisplayName = (displayName) => (Component) => {
    Component.displayName = displayName
    return () => <Component receivedDisplayName={displayName} />
  }
  
  const MyComponent = withDisplayName('MyCurriedHoc')((props) => {
    return <div>{props.receivedDisplayName}</div>
  })
  ```
  
  If we look at the output of `@prefresh/babel-plugin`, we see the following
  
  
  ```js
  const withDisplayName = (displayName) => (Component) => {
    Component.displayName = displayName;
    return () => /* @__PURE__ */ h(Component, {
      receivedDisplayName: displayName
    });
  };
  const MyComponent = withDisplayName("MyCurriedHoc")((props) => {
    return /* @__PURE__ */ h("div", null, props.receivedDisplayName);
  });
  ```
  
  As we can see, the plugin did not save the reference to the component and does not register it for refresh. Interestingly enough in this precise situation, the first change made to the component... Correctly gets updated through HMR (using @web/dev-server). I don't really know why this is happening since the `if (import.meta.hot) {` bit is nowhere to be seen in the transformed code.
  
  The second change however, triggers a full reload of the page (which is normal considering HMR handling has not been injected).
  
  Next I tried storing the first currying stage in a temporary variable, as follows:
  
  ```jsx
  const withDisplayName = (displayName) => (Component) => {
    Component.displayName = displayName
    return () => <Component receivedDisplayName={displayName} />
  }
  
  const withCurriedName = withDisplayName('MyCurriedHoc')
  
  const MyComponent = withCurriedName((props) => {
    return <div>{props.receivedDisplayName}!!!</div>
  })
  ```
  
  With this change, the transformed output becomes:
  
  ```js
  const withDisplayName = displayName => Component => {
    Component.displayName = displayName;
    return () => /* @__PURE__ */h(Component, {
      receivedDisplayName: displayName
    });
  };
  
  const withCurriedName = withDisplayName("MyCurriedHoc");
  const MyComponent = withCurriedName(_c = props => {
    return /* @__PURE__ */h("div", null, props.receivedDisplayName);
  });
  _c2 = MyComponent;
  export const StubbablePlayground = MyComponent;
  
  var _c, _c2;
  
  $RefreshReg$(_c, "MyComponent$withCurriedName");
  $RefreshReg$(_c2, "MyComponent");
  
            if (import.meta.hot) {
              self.$RefreshSig$ = prevRefreshSig;
              self.$RefreshReg$ = prevRefreshReg;
              import.meta.hot.accept(() => {
                try {
                  flushUpdates();
                } catch(e) {
                  import.meta.hot.invalidate();
                }
              });
            }
  ```
  
  Now we can clearly see that HMR handling has been injected as expected, and with this everything works fine.
</details>

Is this a known limitation? It would really help not having to rely on a temporary variable to store the curried HOC before calling it.

I've looked into the code of `@prefresh/babel-plugin` but I'm not knowledgeable enough in Babel to know where to add checks for this myself.

**Comment by JoviDeCroock** [comment]
This is a known limitation if we can't identify the VNode by a name we can't hot-reload

**Comment by jvdsande** [comment]
Hum... So the issue is that 
```js
withDisplayName('MyCurriedHoc')
```
when inline has no name that can be extracted, while 
```js
const withCurriedName = withDisplayName('MyCurriedHoc')
``` 

has a name that can be used to construct the `MyComponent$withCurriedName` I see in the output code?

Isn't it possible to extract `MyComponent$withDisplayName` from the following expression? 
```js
const MyComponent = withDisplayName('MyCurriedHoc')(...)
```

**Comment by JoviDeCroock** [comment]
Not really as there are multiple unnamed funcs in there 😅

**Comment by jvdsande** [comment]
Ah, I see yes. `withDisplayName('MyCurriedHoc')` returns an unnamed function I did not take into account, that will mess things up in the AST.

While I'm here and before closing this, could you tell me why this form does not work either:


```js
const withDisplayName = (displayName, Component) => {
  Component.displayName = displayName
  return () => <Component receivedDisplayName={displayName} />
}

const MyComponent = withDisplayName('MyParameterizedHoc', (props) => {
  return <div>{props.receivedDisplayName}!</div>
})

Transformed output is:

```js
const withDisplayName = (displayName, Component) => {
  Component.displayName = displayName
  return () => <Component receivedDisplayName={displayName} />
}

const MyComponent = withDisplayName('MyParameterizedHoc', (props) => {
  return <div>{props.receivedDisplayName}!</div>
})
```

It looks like in order to qualify as a HOC, the component-like parameter must be the first parameter? Is that also a limitation or is that a design choice?

**Comment by JoviDeCroock** [comment]
Hmm I haven't thought much about that case, it could be that we can fix this, not entirely sure

**Comment by jvdsande** [comment]
Ok 🙂 

For my use case a curried HOC working inline would be perfect, but I could live with a parametrised HOC as long as I can give my parameters first (it's a developer experience requirement). Having to pass the component first to HOC is limiting.

**Comment by jvdsande** [comment]
For the parameter orders it seems it's as simple as changing:
```js
            const firstArgPath = argsPath[0];
            const innerName = inferredName + '$' + calleeSource;
            const foundInside = findInnerComponents(
              innerName,
              firstArgPath,
              callback
            );
            if (!foundInside) {
              return false;
            }
```

To:

```js
            const innerName = inferredName + '$' + calleeSource;
            
            const foundInside = argsPath.some((argPath) => findInnerComponents(
              innerName,
              argPath,
              callback
            ))
            
            if (!foundInside) {
              return false;
            }
```

Around line 100 of `babel/src/index.mjs`

Not sure if this has side-effects though so I'm not confident enough to open a PR, but I tested it locally and it does make the parametrised HOC work as expected

**Comment by JoviDeCroock** [comment]
Feel free to PR it 😅 will test it out with you

**Comment by jvdsande** [comment]
It seems I found a way to make it work for curried HOC too, I'll include this in the PR so that you can review :)

**Comment by jvdsande** [comment]
There you go :) Thanks for you help and let see if we can make this work :)
