### ISSUE TITLE
@prefresh/vite not refreshing

### ISSUE THREAD

**Issue by konsumer** [preactjs/prefresh#454]
I am using these versions:

```
"@prefresh/vite": "^2.2.8"
"vite": "^2.9.1"
"preact": "^10.7.1"

node v17.6.0
```

I do this in vite.config.js

```js
const { defineConfig } = require('vite')
const prefresh = require('@prefresh/vite')
const { resolve } = require('path')

export default defineConfig({
  plugins: [prefresh()],
  resolve: {
    alias: {
      '~': resolve(__dirname, './src'),
      react: 'preact/compat',
      'react-dom': 'preact/compat'
    }
  }
})
```

In the dev-console I see `[vite] hot updated: /src/pages/dashboard.jsx`, but it doesn't reload unless I refresh. I can make a demo project, if needed.

**Comment by JoviDeCroock** [comment]
Can you reproduce it in our tests? Maybe upgrading is enough (v2.9 is new) I am currently on a holiday will chech when I get back

**Comment by konsumer** [comment]
I ended up going with `@preact/preset-vite` (which I think just uses this) and it all seems to work, so I'm not sure what was up.

**Comment by konsumer** [comment]
I can try to make a repro, though, this weekend, too, just top help troubleshoot.

**Comment by lquanx** [comment]
I also use preact  and having the same issue. I had to hit F5 to refresh

**Comment by armincerf** [comment]
I was having the same issue until I added this to my vite.config.ts
```
  optimizeDeps: {
    include: ['preact/hooks', 'preact/compat', 'preact']
  },
```

Now it all works great, might help anyone else having this issue.

(full vite.config.ts)
```
import { defineConfig } from "vite";
import prefresh from "@prefresh/vite";


// https://vitejs.dev/config/
export default defineConfig({
  plugins: [prefresh()],
  optimizeDeps: {
    include: ['preact/hooks', 'preact/compat', 'preact']
  },
  resolve: {
    alias: {
      "react": "preact/compat",
      "react-dom": "preact/compat",
    },
  },
});
```

**Comment by mbenford** [comment]
@armincerf Do you know why `optimizeDeps` is required for HMR to work?
