### ISSUE TITLE
Implement SWC plugin

### ISSUE THREAD

**Issue by nicksrandall** [preactjs/prefresh#487]
I'd like to help port the babel plugin to SWC. Can somebody please explain what the differences are between the react version and the Preact version? I plan to start with the react version (already ported) and make the necessary changes to support Preact.

**Comment by Hideman85** [comment]
+ 1 I also would like to se a SWC implementation therefore it would be a lot faster than babel like vite seem to move to SWC as well for the same reasons https://github.com/vitejs/vite-plugin-react-swc/blob/main/src/refresh-runtime.js

**Comment by JoviDeCroock** [comment]
Hey, on the Babel side of things the two transforms are almost identical. The main difference in the Preact one is that we have [this part](https://github.com/preactjs/prefresh/blob/swc-plugin/packages/babel/src/index.mjs#L469-L536) extra to maintain and reset context references correctly

**Comment by f0am** [comment]
+1

**Comment by colinaaa** [comment]
A SWC plugin has been implemented at https://github.com/swc-project/plugins/pull/326

**Comment by JoviDeCroock** [comment]
It's also published! https://www.npmjs.com/package/@swc/plugin-prefresh
