### ISSUE TITLE
HMR confuses global signals

### ISSUE THREAD

**Issue by rjvdw** [preactjs/prefresh#512]
**Describe the bug**

When using preact with vite, a conflict arises when multiple contexts are defined using the same variable name. Even if these contexts are created in separate files, if they are assigned to the same variable name, they seem to override each other. This only happens when running `npm run dev`, not when running `npm run build` or `npm run preview`.

**To Reproduce**

I created a minimal example exhibiting this behavior: https://github.com/rjvdw/preact-context-bug. Foo.jsx, Bar.jsx and Baz.jsx all define their own context. Foo.jsx and Bar.jsx use `const ctx = createContext`, whereas Baz.jsx uses `const ctxBaz = createContext`.

**Expected behavior**

When running this app, you are presented with three buttons. I would expect each button to only increment the counter directly next to this button, but instead the counters for Foo.jsx and Bar.jsx are linked. I.e. when I increment Foo, Bar is also incremented and vice versa. The counter for Baz _is_ working as intended.

**Comment by rschristian** [comment]
Might be related to #488?

> In the linked issue there's an additional bug report of the `fileHash` being borked when the consumer uses the same default value and variableDeclaration for the `createContext`

**Comment by JoviDeCroock** [comment]
This should be resolved by #524
