### ISSUE TITLE
Prefresh Webpack shouldn't assume the user is using NextJS

### ISSUE THREAD

**Issue by rschristian** [preactjs/prefresh#534]
A user saw this pop up due to a minor version resolution issues w/ a Preact-CLI app which surprised them. Can we check if Next exists before providing this? Or maybe add a more generic error message?

https://github.com/preactjs/prefresh/blob/018f5cc907629b82ffb201c32e948efe4b40098a/packages/webpack/src/index.js#L122-L130

**Comment by JoviDeCroock** [comment]
A generic error message is probably a better shout as we don't support Next.JS anymore either way
